language: node_js
node_js:
  - "node"
dist: trusty
sudo: false
cache: npm
branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build

deploy:
  -
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    bucket: "outcrawl.com"
    local_dir: public
    skip_cleanup: true
    on:
      branch: master
