baseURL: "https://outcrawl.com/"
languageCode: "en-us"
title: "Outcrawl"

metaDataFormat: "yaml"
enableRobotsTXT: true
paginate: 6

blackfriday:
  hrefTargetBlank: true

taxonomies:
  tag: "tags"

permalinks:
  post: "/:slug"

params:
  tagline: "Software development tutorials without nonsense."
  disqusShortname: "outcrawl"
